#include "Enclave_t.h"    // generated by sgx_edger8r
#include <random>

void ecall_add_one(float* input, size_t size, float* output) {
    for (size_t i = 0; i < size; i++) {
        output[i] = input[i] + 1.0f;
    }
}

void ecall_add_noise(float* input, size_t size, float* output) {
    std::mt19937_64 rng;
    std::normal_distribution<float> dist(0.0f, 1.0f);
    for (size_t i = 0; i < size; i++) {
        output[i] = input[i] + dist(rng);
    }
}